In [27]:
!pip install -qqq tabula-py
!pip install pandas -q

In [28]:
from tabula import read_pdf
import pandas as pd

In [29]:
# url_provisory_result = "https://concursos-publicacoes.s3.amazonaws.com/905/publico/905_Edital_009-2024_NotasPreliminares_TO_670442d552f32.pdf?idpub=499901"
url_final_result = "https://concursos-publicacoes.s3.amazonaws.com/905/publico/905_Edital_010-2024_NotasDefinitivas_TO_670ec7ec2591b.pdf?idpub=500028"
tab = read_pdf(url_final_result, pages="all")

In [30]:
for i in range(len(tab)):
    tab[i] = tab[i].dropna(axis=1, how='all')
    
    assert tab[i].shape[1] == 6
    tab[i].columns = ["Name", "Registration", "Mathematics", "CS Fundamentals", "CS Technology", "Total"]

In [31]:
tab = pd.concat(tab, ignore_index=True)

In [32]:
tab = tab.replace("-", None)
tab = tab.dropna(subset=["Total"])

In [33]:
tab = tab.replace(",", ".", regex=True)

tab["Mathematics"] = tab["Mathematics"].astype(float)
tab["CS Fundamentals"] = tab["CS Fundamentals"].astype(float)
tab["CS Technology"] = tab["CS Technology"].astype(float)
tab["Total"] = tab["Total"].astype(float)

In [34]:
tab.describe()

       Mathematics  CS Fundamentals  CS Technology       Total
count   821.000000       821.000000     821.000000  821.000000
mean     11.795371        14.761267       7.721072   34.277710
std       3.712803         4.188138       2.606541    8.672544
min       2.000000         0.000000       0.000000    2.000000
25%       9.000000        12.000000       6.000000   28.000000
50%      12.000000        15.000000       8.000000   34.000000
75%      15.000000        18.000000       9.000000   41.000000
max      20.000000        26.000000      16.000000   60.000000

In [35]:
sorted = tab.sort_values("Total", ascending=False)
sorted.index = range(1, len(sorted) + 1)
sorted.index.name = "Posiçao"

flt = sorted["Name"] == "Joao Pedro Giordani Donasolo"
sorted[flt]

,Name,Registration,Mathematics,CS Fundamentals,CS Technology,Total
Posiçao,,,,,,
68,Joao Pedro Giordani Donasolo,90501119166-2,18.0,19.0,10.0,47.0